# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170822_1950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
